DistinctCodes/scavenger-hunt-backend

- package-lock.json
- package.json
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/dtos/login.dto.ts
- src/auth/dtos/register.dto.ts
- src/auth/guards/rate-limit.guard.ts
- src/users/entities/user.entity.ts
- src/users/users.service.ts
This PR implements the following endpoints:
- **POST /auth/register**: Registers a new user with email, password, and full name.
- **POST /auth/login**: Authenticates a user with email and password and returns a JWT token.
- **GET /auth/me**: Retrieves the current logged-in user's profile.
Also includes:
- Validation for email format and password strength during registration.
- Error handling for invalid login credentials.
- Basic rate limiting to prevent brute force attacks on login.
- Ensures email uniqueness on registration.
closes #3
> Implement auth endpoints with register, login, and user profile retrieval

- package-lock.json
- package.json
- src/app.module.ts
- src/puzzles/dto/create-puzzle.dto.ts
- src/puzzles/dto/update-puzzle.dto.ts
- src/puzzles/dto/verify-puzzle.dto.ts
- src/puzzles/entities/puzzle.entity.ts
- src/puzzles/puzzles.controller.ts
- src/puzzles/puzzles.module.ts
- src/puzzles/puzzles.service.ts
- src/users/entities/user.entity.ts
- src/users/users.entity.ts
This PR adds a new endpoint that allows users to submit answers for puzzles and receive instant feedback.  
If the user solves a puzzle correctly, their progress is updated and they are awarded points.
Implement `POST /puzzles/verify` endpoint that:
- Accepts the user's submitted solution.
- Checks if the submitted answer matches the correct answer.
- If correct:
- Updates the user's list of solved puzzles.
- Awards the corresponding points to the user's profile.
- Returns a success message.
- If incorrect:
- Returns an error message with guidance.
- Handles invalid inputs, missing data, or puzzle not found errors properly.
- Built using NestJS and PostgreSQL.
- Clean, modular service and controller structure.
- Added basic unit tests (using Jest) for puzzle verification logic.
- Swagger …
> Implement Puzzle Verification Endpoint for Scavenger Hunt Game

- src/recent-games/dto/create-game.dto.ts
- src/recent-games/dto/query-games.dto.ts
- src/recent-games/dto/update-game.dto.ts
- src/recent-games/entities/game.entity.ts
- src/recent-games/games.controller.ts
- src/recent-games/games.module.ts
- src/recent-games/games.service.ts
Successfully Implemented Recent Game Completions Endpoint
Developed GET /game-progress/recent-completions/:gameId endpoint to retrieve the latest players who completed a specific game.
Returned structured data including playerId, username, completionTime, score, and rank.
Implemented efficient querying with error handling for invalid or empty game data.
Added unit tests to validate functionality and edge cases.
The endpoint now supports real-time updates for leaderboards and enhances game progress tracking.
> implement endpoint for recent game completions

- src/games/controllers/games.controller.ts
- src/games/providers/games.service.ts
This pull request introduces two critical backend functionalities to the Scavenger Hunt platform's Game module:
---
**Purpose**:  
Enables admin users to permanently remove a game from the database by its ID. This endpoint is protected by Role-Based Access Control (RBAC), ensuring that only authorized users can perform this action.
**Key Features**:
- ✅ Only accessible to users with the **admin** role.
- ✅ Validates the presence of the specified game ID.
- ✅ Returns `404 Not Found` if the game does not exist.
- ✅ Returns `403 Forbidden` if a non-admin tries to delete.
- ✅ Returns `200 OK` on successful deletion with a confirmation message.
- 🛡️ Implements proper error handling for robust response behavior.
**Technical Highlights**:
- Uses NestJS guards for role validation.
- Incorporates …
> Implement Game Deletion (Admin Only) and Retrieve Game by Slug Endpoints

- src/common/dto/pagination.dto.ts
- src/common/dto/sort.dto.ts
- src/common/interfaces/paginated-result.interface.ts
- src/game-session/dto/answer-question.dto.ts
- src/game-session/dto/create-game-session.dto.ts
- src/game-session/dto/game-session-filter.dto.ts
- src/game-session/game-session.controller.ts
- src/game-session/game-session.entity.ts
- src/game-session/game-session.module.ts
- src/game-session/game-session.service.ts
- src/leaderboard/dto/create-leaderboard-entry.dto.ts
- src/leaderboard/dto/leaderboard-filter.dto.ts
- src/leaderboard/dto/leaderboard-stats.dto.ts
- src/leaderboard/dto/update-leaderboard-entry.dto.ts
- src/leaderboard/leaderboard.controller.ts
- src/leaderboard/leaderboard.entity.ts
- src/leaderboard/leaderboard.module.ts
- src/leaderboard/leaderboard.service.ts
This PR implements the `/leaderboard` endpoint for the Scavenger Hunt backend, enabling users to view a paginated list of top players ranked by their score.
---
- Added a `GET /leaderboard` route in the `LeaderboardController`
- Implemented leaderboard ranking logic using SQL window functions (`ROW_NUMBER()` for rank)
- Enabled query parameters `page` (default = 1) and `limit` (default = 20)
- Added validation to ensure `page` and `limit` are positive integers
- Response includes:
- List of users with rank, name, and score
- Metadata: `totalItems`, `totalPages`, `currentPage`
- Gracefully handles empty result sets
- Added basic unit tests and integration tests for the endpoint
---
---
```bash
GET /leaderboard?page=1&limit=10
```
Returns top 10 users with ranks and scores.
---
- …
> Create and Implement the Questions Module with Analytics

- src/games/controllers/games.controller.ts
- src/games/dto/create-game.dto.ts
- src/games/providers/games.service.ts
- Implemented the POST /games API endpoint.
-Restricted access to authenticated admin users only.
- Added input validation using a DTO (CreateGameDto).
- Ensured required fields: title, description, startDate, endDate, and rewardDetails.
- Successfully inserts valid game data into the database.
-Returns the newly created game in the response.
-Added error handling for:
Missing/invalid fields, Unauthorized access
- Followed NestJS best practices for structure and security.
> feat: added secured POST /games endpoint for admin to create new games

- .gitignore
- src/games/controllers/games.controller.ts
- src/games/dto/update-game.dto.ts
- src/games/providers/games.service.ts
- Add game mechanics and puzzle solving logic
- Set up basic game state management
- Implement core puzzle engine features
> feat: implement puzzle game engine core functionality

- src/categories/categories.controller.ts
- src/categories/categories.module.ts
- src/categories/categories.service.ts
- src/categories/dto/create-category.dto.ts
- src/categories/dto/update-category.dto.ts
- src/categories/entities/category.entity.ts
> feat: add categories module with CRUD operations

- src/levels/dto/create-level.dto.ts
- src/levels/dto/update-level.dto.ts
- src/levels/entities/level.entity.ts
- src/levels/levels.controller.spec.ts
- src/levels/levels.controller.ts
- src/levels/levels.module.ts
- src/levels/levels.service.spec.ts
- src/levels/levels.service.ts
I've completed the implementation of the LevelsModule for the Scavenger Hunt backend. The module is clean, independent, and well-integrated with the overall NestJS architecture. It includes:
- levels.module.ts
- levels.service.ts
- levels.controller.ts
- level.entity.ts using TypeORM with PostgreSQL
- DTOs for creating and updating levels
- Proper registration in the app’s main module
The module supports full CRUD operations and lays the foundation for associating levels with puzzles and challenges.
> feat: implemented LevelsModule with CRUD operations and TypeORM

- src/games/games/controllers/game-categories.controller.ts
- src/games/games/providers/game-categories.service.ts
This PR introduces support for bulk user management by implementing transactional operations for creating and deleting multiple users at once.
Closes #27 
1. Clone this branch: `git checkout feat/user-bulk-operations`
2. Run the server: `npm run start:dev`
3. Test endpoints using Postman or HTTP client:
- **POST** `/users/bulk` with array of new users
- **DELETE** `/users/bulk` with array of user IDs
4. Confirm:
- All-or-nothing behavior
- Proper validation
- Correct error handling
---
> Reviewer Tips:
> - Confirm transactional integrity is respected.
> - Validate error handling paths and edge cases.
> - Look for modular, testable service design.
> ✨ Add Bulk User Create and Delete Operations with Transactional Safety

- package-lock.json
- src/app.module.ts
- src/common/decorators/roles.decorator.ts
- src/common/enums/roles.enum.ts
- src/common/guards/roles.guard.ts
- src/developer/developer.controller.ts
- src/developer/developer.module.ts
- src/developer/developer.service.ts
- src/games/controllers/game-categories.controller.ts
- src/games/controllers/games.controller.ts
- src/games/dto/create-category.dto.ts
- src/games/dto/create-game.dto.ts
- src/games/dto/update-category.dto.ts
- src/games/dto/update-game.dto.ts
- src/games/entities/game-category.entity.ts
- src/games/entities/game.entity.ts
- src/games/games.module.ts
- src/games/games.service.ts
- src/games/providers/game-categories.service.ts
- src/games/providers/games.service.ts
- src/puzzle/entities/puzzle.entity.ts
- src/puzzle/puzzle.module.ts
- src/puzzle/puzzle.service.ts
- src/users/entities/user.entity.ts
- src/users/users.service.ts
created and implementated Developer-Tools-Endpoint-implementation
> implementation of Developer-Tools-Endpoint-implementation

- package-lock.json
- src/app.module.ts
- src/feedback/dto/create-feedback.dto.ts
- src/feedback/feedback.controller.spec.ts
- src/feedback/feedback.controller.ts
- src/feedback/feedback.entity.ts
- src/feedback/feedback.module.ts
- src/feedback/feedback.service.spec.ts
- src/feedback/feedback.service.ts
> feat: add player feedback module

- src/app.module.ts
- src/contribution/admin-contribution.controller.ts
- src/contribution/contribution.controller.spec.ts
- src/contribution/contribution.controller.ts
- src/contribution/contribution.module.ts
- src/contribution/contribution.service.spec.ts
- src/contribution/contribution.service.ts
- src/contribution/dto/create-contribution.dto.ts
- src/contribution/dto/leaderboard-query.dto.ts
- src/contribution/dto/review-contribution.dto.ts
- src/contribution/dto/update-contribution.dto.ts
- src/contribution/entities/contribution.entity.ts
- src/contribution/entities/reputation-histroy.entity.ts
- src/contribution/enums/contribution-type.enum.ts
- src/contribution/reputation.service.ts
closes #98
Key Features:
1. Contribution Tracking
Contribution Types: Puzzle creation, bug reporting, bug fixes, reviews, community help, documentation
Status Management: Pending, approved, rejected contributions
Metadata Storage: Additional context for each contribution
2. Reputation Points System
Configurable Point Values: Different points for different contribution types
Level System: Users level up based on reputation points
History Tracking: Complete audit trail of all point changes
> contribution module created

- src/abuse-detection/abuse-detection.controller.spec.ts
- src/abuse-detection/abuse-detection.controller.ts
- src/abuse-detection/abuse-detection.module.ts
- src/abuse-detection/abuse-detection.service.spec.ts
- src/abuse-detection/abuse-detection.service.ts
- src/abuse-detection/dto/create-abuse-detection.dto.ts
- src/abuse-detection/dto/submit-answer.dto.ts
- src/abuse-detection/dto/update-abuse-detection.dto.ts
- src/abuse-detection/entities/abuse-detection.entity.ts
- src/abuse-detection/entities/abuse-record.entity.ts
- src/abuse-detection/interfaces/abuse-detection.interface.ts
- src/app.module.ts
closes #79
Key Features:
1. Tracking System
Records all answer attempts with timestamps, correctness, and IP addresses
Maintains user statistics including total attempts, wrong answers, and consecutive failures
Stores data in TypeORM entities for persistence
2. Abuse Detection
Rapid Submissions: Blocks users who exceed 10 attempts per minute
Repeated Wrong Answers: Blocks after 5 consecutive wrong answers
Configurable thresholds via the AbuseDetectionConfig interface
3. Temporary Blocking
30-minute default block duration (configurable)
Automatic expiration of blocks
Manual unblock capability for admins
> abuse detection feature implemented

- .env.example
- src/app.module.ts
- src/auth/auth.module.ts
- src/auth/controllers/auth.controller.spec.ts
- src/auth/controllers/auth.controller.ts
- src/auth/decorators/auth.decorators.ts
- src/auth/dto/auth.dto.ts
- src/auth/dto/create-auth.dto.ts
- src/auth/dto/update-auth.dto.ts
- src/auth/entities/auth.entity.ts
- src/auth/guards/jwt-auth.guard.ts
- src/auth/guards/roles.guard.ts
- src/auth/services/auth.service.spec.ts
- src/auth/services/auth.service.ts
- src/auth/services/crypto.service.ts
- src/auth/services/email.service.ts
- src/auth/services/wallet.service.ts
- src/auth/strategies/jwt.strategy.ts
- src/interfaces/jwt-payload.interface.ts
- src/types/express.d.ts
- src/user/dto/create-user.dto.ts
- src/user/dto/update-user.dto.ts
- src/user/dto/user.dto.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.spec.ts
- src/user/user.controller.ts
- src/user/user.module.ts
- src/user/user.service.spec.ts
- src/user/user.service.ts
This PR introduces a secure and scalable authentication and user management system for the **NFT Scavenger Hunt Game**. It supports both traditional login via email/password and decentralized authentication using StarkNet wallet signatures. Additionally, the system includes user role management, profile updates, and password recovery capabilities.
---
* Supports email and StarkNet wallet address.
* Passwords are hashed securely using bcrypt before storage.
* Users can log in via email/password.
* On successful login, a JWT access token is issued for session handling.
* Users can sign messages with their wallet for authentication.
* Signature is verified and matched against the registered wallet address.
* Roles supported: `Player` and `Admin`.
* Endpoints are protected using …
> Create the Authentication & User Management System

- src/puzzle-subscription/controllers/notification.controller.ts
- src/puzzle-subscription/controllers/subscription.controller.ts
- src/puzzle-subscription/dto/create-subscription.dto.ts
- src/puzzle-subscription/dto/notification.dto.ts
- src/puzzle-subscription/dto/subscription-response.dto.ts
- src/puzzle-subscription/entities/subscription.entity.ts
- src/puzzle-subscription/puzzle-subscription.module.ts
- src/puzzle-subscription/services/notification.service.ts
- src/puzzle-subscription/services/subscription.service.ts
- src/puzzle-subscription/tests/integration/puzzle-subscription.integration.spec.ts
- src/puzzle-subscription/tests/notification.controller.spec.ts
- src/puzzle-subscription/tests/notification.service.spec.ts
- src/puzzle-subscription/tests/subscription.controller.spec.ts
- src/puzzle-subscription/tests/subscription.service.spec.ts
> implemented the puzzle subscription feature

- src/explanation/controllers/explanation.controller.ts
- src/explanation/controllers/user-solution.controller.ts
- src/explanation/dto/create-explanation.dto.ts
- src/explanation/dto/explanation-response.dto.ts
- src/explanation/dto/update-explanation.dto.ts
- src/explanation/dto/user-solution.dto.ts
- src/explanation/entities/explanation.entity.ts
- src/explanation/entities/user-solution.entity.ts
- src/explanation/guards/admin.guard.ts
- src/explanation/puzzle-explanation.module.ts
- src/explanation/services/explanation.service.ts
- src/explanation/services/user-solution.service.ts
- src/explanation/tests/admin.guard.spec.ts
- src/explanation/tests/explanation.controller.spec.ts
- src/explanation/tests/explanation.service.spec.ts
- src/explanation/tests/integration/puzzle-explanation.integration.spec.ts
- src/explanation/tests/user-solution.service.spec.ts
> created the puzzle explanation system

- src/bookmark/controllers/bookmark.controller.ts
- src/bookmark/controllers/puzzle.controller.ts
- src/bookmark/dto/bookmark-response.dto.ts
- src/bookmark/dto/create-bookmark.dto.ts
- src/bookmark/dto/create-puzzle.dto.ts
- src/bookmark/dto/pagination.dto.ts
- src/bookmark/dto/puzzle-response.dto.ts
- src/bookmark/dto/user-bookmark-response.dto.ts
- src/bookmark/entities/bookmark.entity.ts
- src/bookmark/entities/puzzle.entity.ts
- src/bookmark/puzzle-bookmark.module.ts
- src/bookmark/services/bookmark.service.ts
- src/bookmark/services/puzzle.service.ts
- src/bookmark/tests/bookmark.controller.spec.ts
- src/bookmark/tests/bookmark.service.spec.ts
- src/bookmark/tests/integration/puzzle-bookmark.integration.spec.ts
> bookmark functionality set up

- src/app.module.ts
- src/puzzle/puzzle.controller.spec.ts
- src/puzzle/puzzle.controller.ts
- src/puzzle/puzzle.entity.ts
- src/puzzle/puzzle.module.ts
- src/puzzle/puzzle.service.spec.ts
- src/puzzle/puzzle.service.ts
- src/reward/reward.controller.spec.ts
- src/reward/reward.controller.ts
- src/reward/reward.entity.ts
- src/reward/reward.module.ts
- src/reward/reward.service.spec.ts
- src/reward/reward.service.ts
- Adds admin module functionalities for managing puzzles, rewards, and analytics in the NFT Scavenger Hunt Game.
- Includes full backend support with route protection, services, and entity relationships.
- Added unit tests for puzzle and reward services.
Closes #108
> feat: implement admin panel

- src/app.module.ts
- src/error-report/dto/create-error-report.dto.ts
- src/error-report/dto/error-report-response.dto.ts
- src/error-report/entities/error-report.entity.ts
- src/error-report/enums/error-report-status.enum.ts
- src/error-report/enums/error-report-type.enum.ts
- src/error-report/error-report.controller.spec.ts
- src/error-report/error-report.controller.ts
- src/error-report/error-report.module.ts
- src/error-report/error-report.service.spec.ts
- src/error-report/error-report.service.ts
This PR introduces a **standalone Error Reporting Module** that allows users to report bugs or issues (including puzzle-related errors) they encounter. It is designed to be modular, self-contained, and independent from all other parts of the system.
---
- `id: string` (Primary key)
- `title: string` – Short summary of the error
- `description: string` – Detailed explanation of the error
- `reporterEmail?: string` – Optional email for contact
- `createdAt: Date`
- `status: 'open' | 'resolved' | 'closed'` (default: 'open')
---
- `POST /error-report` – Submit a new error/bug report
- `GET /error-report` – Fetch all submitted reports (admin use)
- `GET /error-report/:id` – Fetch a single report by ID
---
---
- Verified `POST` endpoint creates new reports
- Confirmed `GET` endpoints return …
> Implement Error Reporting Module

- src/app.module.ts
- src/contribution/contribution.controller.ts
- src/contribution/contribution.module.ts
- src/contribution/contribution.service.spec.ts
- src/contribution/contribution.service.ts
- src/contribution/dto/create-contribution.dto.ts
- src/contribution/dto/update-status.dto.ts
- src/contribution/entities/contribution.entity.ts
> Developer Contribution implementation 

- src/app.module.ts
- src/trivia/dto/create-trivia.dto.ts
- src/trivia/dto/update-trivia.dto.ts
- src/trivia/entities/trivia.entity.ts
- src/trivia/trivia.controller.ts
- src/trivia/trivia.module.ts
- src/trivia/trivia.service.spec.ts
- src/trivia/trivia.service.ts
> trivia implementation

- package-lock.json
- package.json
- src/app.module.ts
- src/referral-code/dto/create-referral-code.dto.ts
- src/referral-code/dto/track-referral-code.dto.ts
- src/referral-code/entities/referral-code.entity.ts
- src/referral-code/referral-code.controller.ts
- src/referral-code/referral-code.module.ts
- src/referral-code/referral-code.service.spec.ts
- src/referral-code/referral-code.service.ts
This PR introduces a fully independent Referral Code module for the backend. The module enables players to generate referral codes and track invited users. It is designed to be robust, maintainable, and error-free.
- **ReferralCode Entity**: Stores code, owner, usage count, and creation date.
- **DTOs**: For code generation and usage tracking.
- **Service**: Methods for generating codes, tracking usage, and retrieving codes.
- **Controller**: Endpoints for all main operations.
- **Module**: Standalone and easily integrated.
- **Tests**: High-quality Jest test suite covering all logic and error cases.
- Module imported and registered in `AppModule`.
- All dependencies installed (`@nestjs/common`, `@nestjs/testing`, `@nestjs/typeorm`, `typeorm`, `jest`, etc.).
1. Run `npm install` to ensure …
> feat: Add standalone Referral Code module with full CRUD and tracking

- src/app.module.ts
- src/claim-history/claim-history.controller.ts
- src/claim-history/claim-history.module.ts
- src/claim-history/claim-history.service.ts
- src/claim-history/dto/claim-summary.dto.ts
- src/claim-history/dto/create-claim.dto.ts
- src/claim-history/dto/query-claim.dto.ts
- src/claim-history/entities/claim-history.entity.ts
- src/claim-history/enums/claim-status.enum.ts
This PR implements a complete standalone claim history tracking system that logs and monitors all reward claims by players. The system provides detailed analytics, verification capabilities, and comprehensive claim management.
- Closes - #150 
- ✅ **Detailed Claim Logging**: Track reward ID, name, type, value, and source
- ✅ **Status Management**: Support for pending, claimed, failed, expired, and cancelled states
- ✅ **Metadata Support**: Store additional context (puzzle completion data, streaks, etc.)
- ✅ **Bulk Operations**: Log multiple claims simultaneously for batch rewards
- ✅ **Claim Verification**: Check if players have already claimed specific rewards
- 📊 **Player Statistics**: Individual claim summaries with breakdowns by type/status/source
- 🌍 **Global Analytics**: System-wide …
> feat: Add Comprehensive Reward Claim History System
